library_name = "xmsstamper"
description = "Stamping library for XMS products"
extra_export_sources = ["test_files"]

xms_dependencies = [
    { name = "xmscore", version = "7.0.0" },
    { name = "xmsgrid", version = "9.0.2" },
    { name = "xmsinterp", version = "7.0.1" },
]

python_namespaced_dir = "stamper"

library_sources = [
    "xmsstamper/stamper/XmStamper.cpp",
    "xmsstamper/stamper/XmStamperIo.cpp",
    "xmsstamper/stamper/TutStamping.cpp",
    "xmsstamper/stamper/detail/XmBathymetryIntersector.cpp",
    "xmsstamper/stamper/detail/XmBreaklines.cpp",
    "xmsstamper/stamper/detail/XmGuideBankUtil.cpp",
    "xmsstamper/stamper/detail/XmSlopedAbutmentUtil.cpp",
    "xmsstamper/stamper/detail/XmStampEndCap.cpp",
    "xmsstamper/stamper/detail/XmStampInterpCrossSection.cpp",
    "xmsstamper/stamper/detail/XmStampTests.cpp",
    "xmsstamper/stamper/detail/XmUtil.cpp"
]

library_headers = [
    "xmsstamper/stamper/XmStamper.h",
    "xmsstamper/stamper/XmStamperIo.h",
    "xmsstamper/stamper/detail/XmBathymetryIntersector.h",
    "xmsstamper/stamper/detail/XmBreaklines.h",
    "xmsstamper/stamper/detail/XmGuideBankUtil.h",
    "xmsstamper/stamper/detail/XmSlopedAbutmentUtil.h",
    "xmsstamper/stamper/detail/XmStampEndCap.h",
    "xmsstamper/stamper/detail/XmStamper3dPts.h",
    "xmsstamper/stamper/detail/XmStampInterpCrossSection.h",
    "xmsstamper/stamper/detail/XmUtil.h"
]

testing_headers = [
    "xmsstamper/stamper/TutStamping.t.h",
    "xmsstamper/stamper/detail/XmBathymetryIntersector.t.h",
    "xmsstamper/stamper/detail/XmStampInterpCrossSection.t.h",
    "xmsstamper/stamper/detail/XmStampTests.t.h"
]

pybind_sources = [
    "xmsstamper/python/xmsstamper_py.cpp",
    "xmsstamper/python/stamper/stamper_py.cpp",
    "xmsstamper/python/stamper/XmStamper_py.cpp",
    "xmsstamper/python/stamper/XmStamperIo_py.cpp"
]

pybind_headers = [
    "xmsstamper/python/stamper/stamper_py.h"
]